version: "3"

services:
  fake-balance-api:
    build:
      context: ./projects/apps/fake-balance-api
      dockerfile: Dockerfile.dev
    environment:
      NODE_ENV: development
      PORT: 3001
    volumes:
     - ./projects/apps/fake-balance-api:/opt/app/fake-balance-api
     - /opt/app/fake-balance-api/node_modules
    ports:
      - "3001:3001"
  fake-user-api:
    build:
      context: ./projects/apps/fake-user-api
      dockerfile: Dockerfile.dev
    environment:
      NODE_ENV: development
      PORT: 3002
    volumes:
     - ./projects/apps/fake-user-api:/opt/app/fake-user-api
     - /opt/app/fake-user-api/node_modules
    ports:
      - "3002:3002"
  fake-nginx:
    build:
      context: ./projects/fake-nginx
      dockerfile: Dockerfile.dev
    links:
      - fake-balance-api
      - fake-user-api
      - fake-react-site
    ports:
      - "80:80"
  fake-react-site:
    build:
      context: ./projects/sites/fake-react-site
      dockerfile: Dockerfile.dev
    environment:
      NODE_ENV: development
      PORT: 3000
    volumes:
     - ./projects/sites/fake-react-site:/opt/app/fake-react-site
     - /opt/app/fake-react-site/node_modules
    ports:
      - "3000:3000"
